version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8090:8080"
    volumes:
      - .:/app
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    networks:
      - mynetwork  # Ubah ke nama yang sama dengan yang didefinisikan di bawah

volumes:
  jenkins_home:

networks:
  mynetwork:  # Nama network di docker-compose
    name: nodejs-restfull_mynetwork  # Nama asli network di sistem
    external: true