version: '3.8'

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data_prod:

services:
  db-prod:
    image: mysql:latest
    container_name: sentosa-db-prod
    restart: always
    env_file:
      - .env.prod
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data_prod:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - mynetwork

  api-prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: sentosa-api-prod
    restart: always
    depends_on:
      db-prod:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    volumes:
      # - .:/app
      - /app/node_modules
    command: [ "sh", "-c", "npx prisma migrate deploy --schema=/app/prisma/schema.prisma && pm2-runtime start ecosystem.config.cjs" ]
    networks:
      - mynetwork
