version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./nginx/conf.d/dev.cms.sentosafishery.com.conf:/etc/nginx/conf.d/dev.cms.sentosafishery.com.conf:ro
      # - ./nginx/conf.d/dev.sentosafishery.com.conf:/etc/nginx/conf.d/dev.sentosafishery.com.conf:ro
      # - ./nginx/conf.d/staging.sentosafishery.com.conf:/etc/nginx/conf.d/staging.sentosafishery.com.conf:ro
      # - ./nginx/conf.d/api.sentosafishery.com.conf:/etc/nginx/conf.d/api.sentosafishery.com.conf:ro
      - ./nginx/maintenance:/var/www/html:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - mynetwork
